# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_cards',
                'doc_host': 'https://vasilism.github.io',
                'git_url': 'https://github.com/vasilism/nbdev_cards',
                'lib_path': 'nbdev_cards'},
  'syms': { 'nbdev_cards.card': { 'nbdev_cards.card.Card': ('card.html#card', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__eq__': ('card.html#card.__eq__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__gt__': ('card.html#card.__gt__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__init__': ('card.html#card.__init__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__lt__': ('card.html#card.__lt__', 'nbdev_cards/card.py'),
                                  'nbdev_cards.card.Card.__str__': ('card.html#card.__str__', 'nbdev_cards/card.py')},
            'nbdev_cards.core': { 'nbdev_cards.core.Deck': ('deck.html#deck', 'nbdev_cards/core.py'),
                                  'nbdev_cards.core.Deck.__init__': ('deck.html#deck.__init__', 'nbdev_cards/core.py'),
                                  'nbdev_cards.core.Deck.__str__': ('deck.html#deck.__str__', 'nbdev_cards/core.py')},
            'nbdev_cards.deck': { 'nbdev_cards.deck.Deck': ('deck.html#deck', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Deck.__init__': ('deck.html#deck.__init__', 'nbdev_cards/deck.py'),
                                  'nbdev_cards.deck.Deck.__str__': ('deck.html#deck.__str__', 'nbdev_cards/deck.py')}}}
